### PR TITLE
Implemented the _find query

### PR DESCRIPTION
**Pull request by fjace05**
I've implemented the _find query trying to keep it semi-consistent to a call to GetView method. A new struct type was added that includes the available parameters that are required and optional for the _find query. Since this api endpoint is a POST request simply using the url.Values of the View api doesn't work. A few of the parameters can be JSON objects so they are left as interface types and users should be careful to make sure they set them to something Marshalable.

I've also added a super simple test to make sure the new feature works.

### CODE REVIEW

**Comment by fjace05** [comment]
Hmm, I'm thinking it's building against a previous version of couch (maybe 1.6.1) and the _find endpoint wasn't added until 2.0.

**Comment by rhinoman** [comment]
That's quite possible.  Haven't updated the travis config in a while.
Currently the travis.yml just specifies:

```
  "services": [
    "couchdb"
  ],

```
So it will need to be updated to specifically install couchdb 2.0

**Comment by fjace05** [comment]
Sorry to just get back to this. I do think I've found a way to install couchdb2.0 via TravisCI but I didn't know if you wanted to branch the project and maintain two versions of the library for the two major versions of couchdb since this technically is a breaking change.

**Comment by rhinoman** [comment]
For now, I think I'll just create a tag of the current state, then merge this in.... Looks like the install couchdb script isn't working at the moment.

**Pull request merged**
